package cuid2

import (
	"fmt"
	"strings"
	"testing"
)

func create(t *testing.T) string {
	id := CreateId()
	if id == "" {
		t.Fatalf("Cuid not generated")
	}
	if len(id) != 24 {
		t.Errorf("Not a default 24 len. Got %d", len(id))
	}
	return id
}

func charOfString(input string, index int) string {
	return string(input[index])
}

func TestGeneratesCuid2(t *testing.T) {
	create(t)
}

func TestFirstCharFromAtoZ(t *testing.T) {
	atoz := "abcdefghijklmnopqrstuvwxyz"
	const timesRunTest = 100
	var firstChars [timesRunTest]string
	for i := range timesRunTest {
		id := create(t)
		firstChar := charOfString(id, 0)
		if !strings.Contains(atoz, firstChar) {
			t.Errorf("First char is not from a to z. Found %q\n", firstChar)
		}
		firstChars[i] = firstChar
	}
}

func TestIsCuidFalse(t *testing.T) {
	tests := []string{
		"", "1", "1", "asdf98923jhf90283jh02983hjf02983fh", "afasd as dfas ", "1asdfasdf", "   ",
		CreateId() + CreateId() + CreateId(),
	}
	for _, tt := range tests {
		t.Run(tt, func(t *testing.T) {
			isCuid := IsCuid(tt)
			if isCuid {
				t.Errorf("The input %s should not be a cuid, but it says so.", tt)
			}
		})
	}
}

func TestIsCuidWithValidIds(t *testing.T) {
	// These ids are generated by original library
	tests := []string{
		"tra51en4jnteg5yfch4ww56u",
		"hwfvvcgfp6unxxzcbwbewil8",
		"bu37v7q6sgrgzhagarwz0lpt",
		"vkdfwossmrykise0fpd4bq8x",
		"i7ls2o9hx6rlcjc9ha9tjyu7",
		"l6l6wbqcsiwxx7jvaev1m8ra",
	}
	for _, tt := range tests {
		t.Run(tt, func(t *testing.T) {
			isCuid := IsCuid(tt)
			if !isCuid {
				t.Errorf("The input %s should be a cuid, but it says it is not.", tt)
			}
		})
	}
}

func FuzzTestRandom(f *testing.F) {
	noOfIdsToGenerate := 1000
	for range noOfIdsToGenerate {
		f.Add(CreateId())
	}

	f.Fuzz(func(t *testing.T, id string) {
		if !IsCuid(id) {
			t.Errorf("Either id or isCuid is wrong for: %s", id)
		}
	})
}

func TestConfigurability(t *testing.T) {
	random := func() float64 { return 0 }
	counter := func() int64 { return 0 }
	length := 3
	fingerprint := "abc"
	fn := Init(random, counter, length, fingerprint)
	id := fn()
	if id == "" {
		t.Errorf("Custom function didn't return proper id")
	}
	if len(id) != 3 {
		t.Errorf("Id is not of len 3. Got %d", len(id))
	}
}

func TestLengthWithFullCustomization(t *testing.T) {
	minLen := 2
	maxLen := 32
	for tt := minLen; tt <= maxLen; tt++ {
		t.Run(fmt.Sprintf("with length %d", tt), func(t *testing.T) {
			createId := Init(DefaultRandom, DefaultCounter, tt, DefaultFingerprint)
			id := createId()
			fmt.Printf("Created id %q\n", id)
			if len(id) != tt {
				t.Errorf("Expected id of len %d. Got %d\n", tt, len(id))
			}
		})
	}
}

func TestLengthOnlyCustomization(t *testing.T) {
	minLen := 2
	maxLen := 32
	for tt := minLen; tt <= maxLen; tt++ {
		t.Run(fmt.Sprintf("with length %d", tt), func(t *testing.T) {
			id, err := CreateIdOf(tt)
			fmt.Printf("Created id %q\n", id)
			if len(id) != tt && err == nil {
				t.Errorf("Expected id of len %d. Got %d\n", tt, len(id))
			}
		})
	}
}

func TestInvalidLength(t *testing.T) {
	tests := []int{1, 33, 0, -1}
	for _, tt := range tests {
		t.Run(fmt.Sprintf("with length %d", tt), func(t *testing.T) {
			_, err := CreateIdOf(tt)
			if err == nil || err.Error() != "len should be between 2 and 32" {
				t.Errorf("Expected error 'len should be between 2 and 32', got %v", err)
			}
		})
	}
}
